### ISSUE TITLE
Sticker generator woes

### ISSUE THREAD

**Issue by Dregu** [Malacath-92/Playlunky#1]
A lot of editors and therefore character mods use transparent as rgba(255,255,255,0), although the game and presumably playlunky expect rgba(0,0,0,0). This causes the sticker generator to put all white squares instead of characters in the quick select etc... You should make sure all transparent or near transparent pixels are converted to black or weird things happen.

Also the custom tile positions (8x14 and 8x15, presumably 0-indexed XxY) for sticker and journal graphics make no sense. I assume you meant the two-or-so tiles to the right of *petting*, but currently they're both using 8x14, journal just using a larger area of it. 8x15 is not even possible. Exact pixel coordinates would be nice.

**Comment by Malacath-92** [comment]
1. Right, I was taking care of that first issue you mentioned in the png->DDS conversion but not for the sticker gen.
2. I will verify the tile positions and also give exact pixel coordinates. We will maybe move over to generating the merged sheets during extraction in Modlunky so this might not be an issue that really matters in the future.

**Comment by Malacath-92** [comment]
You were absolutely right about the second issue, I mixed up X and Y when moving to the next tile so I wrote `8x15` rather than ´9x14´
I updated the wiki and readme.txt as well as included exact pixel coords.

**Comment by Malacath-92** [comment]
Fixed in [v0.4.0](https://github.com/Malacath-92/Playlunky/releases/tag/v0.4.0)
